# Generated by Django 2.2.6 on 2019-12-17 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20191217_1846'),
    ]

    operations = [
        migrations.AddField(
            model_name='cloth',
            name='color',
            field=models.CharField(default='blue', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cloth',
            name='item',
            field=models.CharField(default='socks', max_length=50),
            preserve_default=False,
        ),
    ]
