# Generated by Django 2.2.6 on 2019-12-17 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_auto_20191217_1855'),
    ]

    operations = [
        migrations.AddField(
            model_name='teddy',
            name='clothes',
            field=models.ManyToManyField(to='main_app.Cloth'),
        ),
    ]
