# Generated by Django 2.2.6 on 2019-12-18 01:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_teddy_clothes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=250)),
                ('teddy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Teddy')),
            ],
        ),
    ]
